### ISSUE TITLE
Plugin config options added to config file

### ISSUE THREAD

**Issue by meskarune** [HalosGhost/ailur#35]
I have a suggestion for adding config.plugins = {} to the configuration file for people to add plugin configuration stuff. I would like to be able to set debugging for plugins and for the main bot separately. This way you can hide irc server messages but still see plugin debug messages. People can also add other plugin specific options there if they come up in the future. Maybe also things like verbosity -- if plugins should fail silently or have help message responses.

**Comment by HalosGhost** [comment]
This makes me wonder if we should mirror the new user-settings module for plugin settings. thoughts?

**Comment by meskarune** [comment]
Oh, like keep the plugin settings in the DB instead of the config file? Did you also want to keep stuff like secrets in the DB?

**Comment by HalosGhost** [comment]
I was thinking about it, yeah. Thoughts?

**Comment by HalosGhost** [comment]
Also solved via the `users` module/table and `userset` plugin.
