### ISSUE TITLE
Set plugin

### ISSUE THREAD

**Issue by HalosGhost** [HalosGhost/ailur#47]
I think having a unified interface among plugins for managing user settings would be incredibly useful and pleasant.

The only requirement is that some settings need to be admin-gated. By default, the only one that matters is probably the admin setting itself. However, I can imagine having a new field required for the settings table to store if a setting should require admin authorization.

Food for thought.

**Comment by oatberry** [comment]
> However, I can imagine having a new field required for the settings table to store if a setting should require admin authorization.
By this, do you mean a new setting in config.lua?

**Comment by HalosGhost** [comment]
Not really. There are a few different ways this could be implemented. One (the one I had imagined) would be to have a second table that just tracks the available user settings along with a field that says whether or not that setting is adjustable by users. The second table (the one we currently have), would then actually track the values for given settings (foreign-keying to the aforementioned table). This would allow plugins to declare new settings and decide if anyone or just admins should be able to modify a setting for themselves.

For example, `manage` could declare the `admin` setting and require that a user must be an admin to modify their value for that setting. Effectively, this would mean the first admin must be added by modifying the database, but all future admins could be added by that first (or any subsequent) admin. This is just a hypothetical, but either way, a `set` plugin would be a good usability win as many of the plugins will see benefits from moving things into settings.

**Comment by meskarune** [comment]
Is this almost complete? I think there needs to be a way to have a default admin and add admins. Maybe we could get the status on this and what is left to do?

**Comment by HalosGhost** [comment]
as far as I know, this is completed via the `users` module and `userset` plugin.

A default admin and an associated control for the default admin to be able to modify user's internal settings (those found on the `users` table), is not in scope for this issue, but is a great idea. Open a new issue for it whenever you're ready!
